[fileserver]
port = 8082

[database]
type = mysql
host = db
port = 3306
user = seafile
password = c6e3da44-dadf-43eb-8571-7862f4a7b89d
db_name = seafile_db
connection_charset = utf8

[notification]
enabled = false
host = 127.0.0.1
port = 8083
log_level = info
jwt_private_key = +pz175s!7u_#uh13!gk202!k@!q)9b#xlmlcfv#(myq0-xg3g

